### ISSUE TITLE
Error in manage start

### ISSUE THREAD

**Issue by guilherme-funchal** [AnonSolutions/django-aries-community#15]
./manage start
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 4040: Conexão recusada
Using http://172.17.0.1:9000 as ledger and http://trustee-agent:8042 as the agent endpoint.

**Comment by ianco** [comment]
I've never seen that error before, does it happen consistently?

**Comment by guilherme-funchal** [comment]
Yes, when I start. 

What's service use this port ?

**Comment by ianco** [comment]
Aha it's this line of code:  https://github.com/AnonSolutions/django-aries-community/blob/master/docker/manage#L150

So it's not an error actually, and all the docker containers should still start up.

This is checking to see if there is an ngrok process running exposing the trustee agent on a public url (which is required to work with mobile agents)

There's an ngrok script you can run (run the ngrok script in a separate bash shell before you run docker) and then you shouldn't see this error

**Comment by ianco** [comment]
https://github.com/AnonSolutions/django-aries-community/blob/master/aries_community_demo/ngrok-trustee.sh

**Comment by ianco** [comment]
When you're running ngrok it looks something like this:

(venv) Ians-MBP:docker icostanzo$ INDY_NETWORK=bcovrin-test ./manage start
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   396  100   396    0     0  79200      0 --:--:-- --:--:-- --:--:-- 79200
Using http://test.bcovrin.vonx.io as ledger and https://ade7cf8f.ngrok.io as the agent endpoint.

**Comment by guilherme-funchal** [comment]
Thanks Ian

Corrected this error, you will report another one in a new task.

**Comment by guilherme-funchal** [comment]
aries-django_1   | Stderr o_faber_college: python3: can't open file '../venv/bin/aca-py': [Errno 2] No such file or directory

**Comment by guilherme-funchal** [comment]
It's working
